### ISSUE TITLE
Build is missing `store.d.ts`

### ISSUE THREAD

**Issue by arbourd** [karimsa/rsxjs#53]
## Description

The bundle does not include type files for Store.

## Steps to Reproduce (for bugs)

- `npm run build`
- Check dist/
- Lots of type errors

<img width="1179" alt="Screen Shot 2021-07-07 at 5 11 24 PM" src="https://user-images.githubusercontent.com/7211830/124829269-692a0b80-df46-11eb-9496-0182a604e94e.png">

**Comment by arbourd** [comment]
This is caused by Rollup: `tsc` works just fine.

**Comment by karimsa** [comment]
Hey, thanks for your contribution! I think I have fixed this issue on master - we're now using `tsc` to generate the declaration files, and `esbuild` to do the bundling.

Could you please verify that this is working for you? If you need a release version, I can release a `next` version.

**Comment by arbourd** [comment]
A release would be great! Thank you.

**Comment by karimsa** [comment]
No worries! A release is up `v0.6.1-1` - you can install with `npm install rsxjs@next`.

Please note that your typescript config will need to include `es2015` or later in the libraries section (i.e. `{ "lib": ["esnext"] }`).

**Comment by arbourd** [comment]
Ya, if you we're worried about Fokoud it's running on Node 14 with ES2016 so this builds just fine. 

Thanks!

**Comment by karimsa** [comment]
Perfect! Dropping node v6/8 support was long overdue.

Just curious: which parts of rsxjs are you guys still using?

---

Released a stable copy with tag `v1.0.0` (major upgrade, since this will now break on old node versions).

**Comment by arbourd** [comment]
Ah whatever was there before: `WaitGroup`, `RedisStore`, `Mutex`, `Deferral`, `Semaphore`, `Breaker`
